/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.EventQueue;
import javax.swing.JOptionPane;

/**
 *
 * @author George Vasquez
 */
public class Teorema_6 extends javax.swing.JFrame {

    /**
     * Creates new form Teorema_6
     */
    public Teorema_6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFn = new javax.swing.JTextField();
        jTextFr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        labelN = new javax.swing.JLabel();
        labelR = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelResultado = new javax.swing.JLabel();
        botonCalcular = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelN2 = new javax.swing.JLabel();
        labelR2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CONCEPTO Y FORMULA", jPanel1);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("____________________________");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(190, 80, 320, 20);

        jTextFn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFnKeyReleased(evt);
            }
        });
        jPanel2.add(jTextFn);
        jTextFn.setBounds(40, 40, 60, 30);

        jTextFr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFrActionPerformed(evt);
            }
        });
        jTextFr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFrKeyReleased(evt);
            }
        });
        jPanel2.add(jTextFr);
        jTextFr.setBounds(40, 110, 60, 30);

        jLabel2.setFont(new java.awt.Font("Verdana Pro Cond Light", 0, 48)); // NOI18N
        jLabel2.setText("=");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(140, 40, 60, 120);

        labelN.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelN.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelN.setText("n");
        jPanel2.add(labelN);
        labelN.setBounds(210, 50, 140, 30);

        labelR.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelR.setText("r");
        jPanel2.add(labelR);
        labelR.setBounds(230, 115, 40, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("-");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(370, 110, 13, 44);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText(")");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(440, 110, 14, 44);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("RESULTADO =");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 190, 160, 22);

        labelResultado.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelResultado.setText("------------");
        jPanel2.add(labelResultado);
        labelResultado.setBounds(180, 180, 330, 40);

        botonCalcular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonCalcular.setText("CALCULAR");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });
        jPanel2.add(botonCalcular);
        botonCalcular.setBounds(20, 250, 130, 40);

        botonLimpiar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonLimpiar.setText("LIMPIAR");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(botonLimpiar);
        botonLimpiar.setBounds(370, 250, 120, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("!");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(360, 40, 30, 44);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("!");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(280, 110, 20, 44);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("!");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(460, 110, 30, 44);

        labelN2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelN2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelN2.setText("n");
        jPanel2.add(labelN2);
        labelN2.setBounds(320, 120, 40, 30);

        labelR2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelR2.setText("r");
        jPanel2.add(labelR2);
        labelR2.setBounds(400, 120, 40, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("(");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(300, 110, 14, 44);

        jLabel4.setFont(new java.awt.Font("Verdana Pro Cond Light", 0, 90)); // NOI18N
        jLabel4.setText("(");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 20, 60, 120);

        jLabel8.setFont(new java.awt.Font("Verdana Pro Cond Light", 0, 90)); // NOI18N
        jLabel8.setText(")");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(110, 20, 60, 120);

        jTabbedPane1.addTab("CALCULADORA ", jPanel2);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        labelR.setText("r");
        labelN.setText("n");
        labelR2.setText("r");
        labelN2.setText("n");
        jTextFn.setText("");
        jTextFr.setText("");
        labelResultado.setText("----------");
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void jTextFnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFnKeyReleased
        labelN.setText(jTextFn.getText());
        labelN2.setText(jTextFn.getText());
    }//GEN-LAST:event_jTextFnKeyReleased

    private void jTextFrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFrKeyReleased
        labelR.setText(jTextFr.getText());
        labelR2.setText(jTextFr.getText());
    }//GEN-LAST:event_jTextFrKeyReleased

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
       int n;
       int r;
       
       try{
       n=Integer.parseInt(jTextFn.getText());
       r=Integer.parseInt(jTextFr.getText());
        
        if (r>=0 && n>=0){            
           Funcion t6= new Funcion();
           
           try{
           labelResultado.setText(Double.toString(t6.teoremaSeis(n,r)));
           }catch(Exception e){
           System.out.println(e);
           }
  
        }
        else{
        JOptionPane.showMessageDialog(null,"Error no se haceptan numeros negativos");
        }
        
       }catch(Exception e){
       JOptionPane.showMessageDialog(null," porfavor verifique sus datos\n vuelva a intentar "+ e);
       
       }
        
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          Menu regresarMenu = new Menu();
        regresarMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teorema_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teorema_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teorema_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teorema_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teorema_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFn;
    private javax.swing.JTextField jTextFr;
    private javax.swing.JLabel labelN;
    private javax.swing.JLabel labelN2;
    private javax.swing.JLabel labelR;
    private javax.swing.JLabel labelR2;
    private javax.swing.JLabel labelResultado;
    // End of variables declaration//GEN-END:variables
}
