/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author vasqu
 */
public class Teorema_12_Ind extends javax.swing.JFrame {

    /**
     * Creates new form Teorema_12_dependientes
     */
    private List<JTextField> texfieldAgregar;
    private List<JLabel> labelAgregar;
    int indice;
    //String indiceLbGuia;
    String indiceLbInfo = "";
    String datos = "";

    public Teorema_12_Ind() {
        setUndecorated(true);
        setBackground(new Color(0, 0, 0, 0));
        initComponents();
        jPanel1.setBackground(new Color(249, 207, 147));
        panelAgregar.setBackground(new Color(249, 207, 147));

        setLocationRelativeTo(null);
        texfieldAgregar = new ArrayList<>();
        labelAgregar = new ArrayList<>();
        indice = 0;
        texfieldAgregar.add(textfielUno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        botonQuitar = new javax.swing.JButton();
        botonAgregarElemeto = new javax.swing.JButton();
        labelRespuesta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelAgregar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textfielUno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelMostrarUnionPA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("LIMPIAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 153, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("CALCULAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        botonQuitar.setBackground(new java.awt.Color(0, 153, 255));
        botonQuitar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonQuitar.setText("ELIMINAR");
        botonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarActionPerformed(evt);
            }
        });

        botonAgregarElemeto.setBackground(new java.awt.Color(0, 153, 255));
        botonAgregarElemeto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonAgregarElemeto.setText("AGREAGAR P(A2)");
        botonAgregarElemeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarElemetoActionPerformed(evt);
            }
        });

        labelRespuesta.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        labelRespuesta.setText("---");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 33)); // NOI18N
        jLabel2.setText("TOTAL:");

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        panelAgregar.setLayout(new java.awt.GridLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 33)); // NOI18N
        jLabel1.setText("P(A1) ");
        jLabel1.setToolTipText("");
        panelAgregar.add(jLabel1);

        textfielUno.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textfielUno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textfielUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfielUnoActionPerformed(evt);
            }
        });
        panelAgregar.add(textfielUno);

        jScrollPane1.setViewportView(panelAgregar);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("=");

        jScrollPane2.setBorder(null);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        labelMostrarUnionPA.setBackground(new java.awt.Color(249, 207, 147));
        labelMostrarUnionPA.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        labelMostrarUnionPA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMostrarUnionPA.setText("P(A1)");
        labelMostrarUnionPA.setOpaque(true);
        jScrollPane2.setViewportView(labelMostrarUnionPA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(labelRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(botonAgregarElemeto, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(labelRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAgregarElemeto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        while (indice != 0) {
            quitarComponentes();
            agregarLabelGuiaUnionPA();

        }
        indiceLbInfo = "";
        botonAgregarElemeto.setText("AGREGAR P(A2)");
        botonQuitar.setText("ELIMINAR");
        texfieldAgregar.get(0).setText("");

        labelRespuesta.setText("---");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try {
            labelRespuesta.setText(Double.toString(operacionTeorema12()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al ingresar sus datos \nPor favor vuelva a intentar\n" + e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void botonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarActionPerformed
        quitarComponentes();
        agregarLabelGuiaUnionPA();

        if (texfieldAgregar.size() > 1) {
            botonAgregarElemeto.setText("AGREGAR P(A" + Integer.toString(texfieldAgregar.size() + 1) + ")");
            botonQuitar.setText("ELIMINAR P(A" + Integer.toString(texfieldAgregar.size()) + ")");
        } else {
            botonAgregarElemeto.setText("AGREGAR P(A2)");
            botonQuitar.setText("ELIMINAR");
        }
    }//GEN-LAST:event_botonQuitarActionPerformed

    private void botonAgregarElemetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarElemetoActionPerformed
        agregarTexfiel();
        botonAgregarElemeto.setText("AGREGAR P(A" + Integer.toString(texfieldAgregar.size() + 1) + ")");
        botonQuitar.setText("ELIMINAR P(A" + Integer.toString(texfieldAgregar.size()) + ")");
        agregarLabelGuiaUnionPA();
    }//GEN-LAST:event_botonAgregarElemetoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Teorema_12 regresarMenu = new Teorema_12();
        regresarMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    int xx;
    int xy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);

    }//GEN-LAST:event_jPanel1MouseDragged

    private void textfielUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfielUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfielUnoActionPerformed

    //mis metodos
    void agregarTexfiel() {
        indice++;
        JTextField txt = new JTextField();
        JLabel lbl = new JLabel("P(A" + (indice + 1) + ")");
        //este codigo me permite cambiar el tipo de letra, negrita o simple y tamaño de letra
        lbl.setFont(new Font("Times New Roman", Font.BOLD, 30));
        //con esto estoy centrando el texto dentro de mi textfiel
        txt.setHorizontalAlignment(JTextField.CENTER);
        txt.setFont(new Font("Tahoma", Font.BOLD, 30));
        panelAgregar.add(lbl);
        panelAgregar.add(txt);
        texfieldAgregar.add(txt);
        labelAgregar.add(lbl);
        indiceLbInfo = "";
        panelAgregar.updateUI();
        //quitar al terminar 
        /* System.out.println("boton agragar");
        System.out.println("tamaño del arrayLyst: texfeil " + texfieldAgregar.size());
        System.out.println("tama label es " + labelAgregar.size());
        System.out.println("el valor del indice es: " + indice);
        System.out.println("-------------\n");*/

    }

    void quitarComponentes() {

        //con esta instruccion elimino el componente dentro de nuestro progama en tiempo de ejecucion
        //primero digo que me elimine del panel el labol que se localiza en el arrayList segun el indice que le pase
        if (indice >= 1) {
            panelAgregar.remove(texfieldAgregar.get(indice));
            texfieldAgregar.remove(indice);
            indice--;
            panelAgregar.remove(labelAgregar.get(indice));
            labelAgregar.remove(indice);
            panelAgregar.updateUI();
            /*System.out.println("Boton eliminar");
            System.out.println("tamaño del texfiel:  " + texfieldAgregar.size());
            System.out.println("tamaño del label:  " + labelAgregar.size());
            System.out.println("tama del indice " + indice);
            System.out.println("-------------------------\n");*/

            if (indice == 0) {
                labelAgregar.clear();
                panelAgregar.updateUI();
                indice = 0;
                /*System.out.println("tamaño del texfiel:  " + texfieldAgregar.size());
                System.out.println("tamaño del label:  " + labelAgregar.size());
                System.out.println("tama del inice " + indice);*/

            }

        }

    }

    double operacionTeorema12() {

        double total = 1;
        for (int i = 0; i < texfieldAgregar.size(); i++) {
            total *= Double.parseDouble(texfieldAgregar.get(i).getText().replaceAll("\\s+", ""));
        }
        return total;
    }

    void agregarLabelGuiaUnionPA() {
        String inicio = "P(A1";

        for (int i = 0; i < indice; i++) {
            inicio += "∩PA" + (i + 2);

        }

        labelMostrarUnionPA.setText(inicio + ")");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teorema_12_Ind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teorema_12_Ind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teorema_12_Ind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teorema_12_Ind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teorema_12_Ind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarElemeto;
    private javax.swing.JButton botonQuitar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelMostrarUnionPA;
    private javax.swing.JLabel labelRespuesta;
    private javax.swing.JPanel panelAgregar;
    private javax.swing.JTextField textfielUno;
    // End of variables declaration//GEN-END:variables
}
