/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author George Vasquez
 */
public class Teorema_7 extends javax.swing.JFrame {

    /**
     * Creates new form Teorema_7
     */
    public Teorema_7() {
        initComponents();
          //para centrar en pantalla ui al iniciar
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPA = new javax.swing.JTextField();
        jTextFieldPB = new javax.swing.JTextField();
        jTextFieldPAUB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelResultado = new javax.swing.JLabel();
        botonResultado = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        botonLimpiar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CONCEPTO Y FORMULA", jPanel1);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("P(AUB) =");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 120, 170, 39);

        jTextFieldPA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextFieldPA);
        jTextFieldPA.setBounds(170, 30, 90, 40);

        jTextFieldPB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextFieldPB);
        jTextFieldPB.setBounds(310, 30, 90, 40);

        jTextFieldPAUB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPAUB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTextFieldPAUB);
        jTextFieldPAUB.setBounds(448, 30, 90, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("+");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(277, 40, 20, 20);

        jLabel3.setText("P(A)");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(200, 70, 34, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(417, 40, 20, 20);

        jLabel5.setText("P(A∩B)");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(480, 70, 50, 14);

        jLabel6.setText("P(B)");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(340, 70, 30, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("P(AUB) =");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 30, 179, 39);

        labelResultado.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelResultado.setText("-------");
        jPanel2.add(labelResultado);
        labelResultado.setBounds(170, 115, 290, 50);

        botonResultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonResultado.setText("CALCULAR");
        botonResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonResultadoActionPerformed(evt);
            }
        });
        jPanel2.add(botonResultado);
        botonResultado.setBounds(30, 230, 110, 40);

        botonLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonLimpiar.setText("LIMPIAR");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(botonLimpiar);
        botonLimpiar.setBounds(440, 230, 110, 40);

        jTabbedPane1.addTab("CALCULADORA TEOREMA 7", jPanel2);

        botonLimpiar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonLimpiar1.setText("MENU");
        botonLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(botonLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(19, 19, 19)
                .addComponent(botonLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        labelResultado.setText("-------");
        jTextFieldPB.setText("");
        jTextFieldPAUB.setText("");
        jTextFieldPA.setText("");
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResultadoActionPerformed
      Funcion t7= new Funcion();
      double resultado;
      try{
      resultado= t7.teoremaSiete((float) Double.parseDouble(jTextFieldPA.getText()), (float) Double.parseDouble(jTextFieldPB.getText()), (float) Double.parseDouble(jTextFieldPAUB.getText()));
     //para el redonde usamos el metodo Math 
      labelResultado.setText(Double.toString((double)Math.round(resultado * 100)/100));
     }catch(Exception e){
         JOptionPane.showMessageDialog(null,"Error al ingresar los datos\nPor favor vuelva a intentar\n"+ e);
         
     }
    }//GEN-LAST:event_botonResultadoActionPerformed

    private void botonLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiar1ActionPerformed
       Menu regresarMenu = new Menu();
        regresarMenu.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_botonLimpiar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teorema_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teorema_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teorema_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teorema_7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teorema_7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonLimpiar1;
    private javax.swing.JButton botonResultado;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldPA;
    private javax.swing.JTextField jTextFieldPAUB;
    private javax.swing.JTextField jTextFieldPB;
    private javax.swing.JLabel labelResultado;
    // End of variables declaration//GEN-END:variables
}
